### PR TITLE
Troll Menu Added

### PR DESCRIPTION
**Pull request by jakeyboi1**
This creates a troll menu, under the administration player list, after selecting a player! Meaning you can do these options to any player you select from the player list!

What this adds:

- Option to kill selected player!
- Option to make selected player invisible
- Option to lightning strike selected player
- Option to set selected player on fire
- Option to teleport selected player to heaven (really high in the sky)

Was going to add more but figured I will offer the PR with these additions, and if it is merged I will add more. Did not want too add a whole bunch for it too not be something you guys want to add. Made the changes from before, all worked on my end hopefully this looks good!

### CODE REVIEW

**Comment by James-the-Coding-Gamer** [comment]
love this will test it tonight lol

**Comment by James-the-Coding-Gamer** [comment]
> This creates a troll menu, under the administration player list, after selecting a player! Meaning you can do these options to any player you select from the player list!
> 
> What this adds:
> 
> * Option to kill selected player!
> * Option to make selected player invisible
> * Option to lightning strike selected player
> * Option to set selected player on fire
> * Option to teleport selected player to heaven (really high in the sky)
> 
> Was going to add more but figured I will offer the PR with these additions, and if it is merged I will add more. Did not want too add a whole bunch for it too not be something you guys want to add. Made the changes from before, all worked on my end hopefully this looks good!



works but only client side for fire and the lighting . anyway it can be done so anyone around them can see the fire and lighting it ?

**Comment by jakeyboi1** [comment]
> > This creates a troll menu, under the administration player list, after selecting a player! Meaning you can do these options to any player you select from the player list!
> > What this adds:
> > 
> > * Option to kill selected player!
> > * Option to make selected player invisible
> > * Option to lightning strike selected player
> > * Option to set selected player on fire
> > * Option to teleport selected player to heaven (really high in the sky)
> > 
> > Was going to add more but figured I will offer the PR with these additions, and if it is merged I will add more. Did not want too add a whole bunch for it too not be something you guys want to add. Made the changes from before, all worked on my end hopefully this looks good!
> 
> works but only client side for fire and the lighting . anyway it can be done so anyone around them can see the fire and lighting it ?

Not that I am aware of not the lightning native does not have an option for network, the fire maybe if the object is set to networked, but even then not sure. If this gets merged I plan on adding some more features to it though so we shall see. It does work on all players in the server though, not just your player character?

**Comment by James-the-Coding-Gamer** [comment]
> > > This creates a troll menu, under the administration player list, after selecting a player! Meaning you can do these options to any player you select from the player list!
> > > What this adds:
> > > 
> > > * Option to kill selected player!
> > > * Option to make selected player invisible
> > > * Option to lightning strike selected player
> > > * Option to set selected player on fire
> > > * Option to teleport selected player to heaven (really high in the sky)
> > > 
> > > Was going to add more but figured I will offer the PR with these additions, and if it is merged I will add more. Did not want too add a whole bunch for it too not be something you guys want to add. Made the changes from before, all worked on my end hopefully this looks good!
> > 
> > 
> > works but only client side for fire and the lighting . anyway it can be done so anyone around them can see the fire and lighting it ?
> 
> Not that I am aware of not the lightning native does not have an option for network, the fire maybe if the object is set to networked, but even then not sure. If this gets merged I plan on adding some more features to it though so we shall see. It does work on all players in the server though, not just your player character?

no it works on both my self and the player just only on each only client  is the visuals like the fire and lighting  but i see then fall or die when used yes just not see  the lighting or fire lol it would be funnier to troll them if everyone around the one set on fire and or lighting struck could see it

**Comment by jakeyboi1** [comment]
Perfect! Just glad it works on everyone. If it gets merged I plan on adding some more stuff to it over time, and I'll look into seeing if I could make that happen aswell

**Comment by outsider31000** [comment]
you can sync the lightning by send it to al clients and make sure only the coords are set to the target. you can get the coords in server side before sending to all clients so whoever is cose will see it.

**Comment by jakeyboi1** [comment]
> you can sync the lightning by send it to al clients and make sure only the coords are set to the target. you can get the coords in server side before sending to all clients so whoever is cose will see it.

Just included this into the pr!

**Comment by James-the-Coding-Gamer** [comment]
ill test this shortly !

**Comment by James-the-Coding-Gamer** [comment]
would you not need to add to the AllowedGroups  in the config ?

```
        { group = { "admin" }, command = "vorp.staff.SetPlayerOnFire" },
        { group = { "admin" }, command = "vorp.staff.LightningStrikePlayer" },
        { group = { "admin" }, command = "vorp.staff.TPToHeaven" },
        { group = { "admin" }, command = "vorp.staff.InvisPlayer" },
        { group = { "admin" }, command = "vorp.staff.KillPlayer" },
        { group = { "admin" }, command = "vorp.staff.OpenTrollActions" },
```

**Comment by jakeyboi1** [comment]
> would you not need to add to the AllowedGroups in the config ?
> 
> ```
>         { group = { "admin" }, command = "vorp.staff.SetPlayerOnFire" },
>         { group = { "admin" }, command = "vorp.staff.LightningStrikePlayer" },
>         { group = { "admin" }, command = "vorp.staff.TPToHeaven" },
>         { group = { "admin" }, command = "vorp.staff.InvisPlayer" },
>         { group = { "admin" }, command = "vorp.staff.KillPlayer" },
>         { group = { "admin" }, command = "vorp.staff.OpenTrollActions" },
> ```

Yup no totally right good catch, just added this in

**Comment by James-the-Coding-Gamer** [comment]
> > you can sync the lightning by send it to al clients and make sure only the coords are set to the target. you can get the coords in server side before sending to all clients so whoever is cose will see it.
> 
> Just included this into the pr!

works ! 
now just the fire and this is prefect but i love it so far !!

**Comment by jakeyboi1** [comment]
> > > you can sync the lightning by send it to al clients and make sure only the coords are set to the target. you can get the coords in server side before sending to all clients so whoever is cose will see it.
> > 
> > 
> > Just included this into the pr!
> 
> works ! now just the fire and this is prefect but i love it so far !!

Replace line 208 in client.lua with this ```  local object = CreateObject(model, 0, 0, 0, true, false, false)  ``` that might do it, if that works let me know.

**Comment by James-the-Coding-Gamer** [comment]
> > > > you can sync the lightning by send it to al clients and make sure only the coords are set to the target. you can get the coords in server side before sending to all clients so whoever is cose will see it.
> > > 
> > > 
> > > Just included this into the pr!
> > 
> > 
> > works ! now just the fire and this is prefect but i love it so far !!
> 
> Replace line 208 in client.lua with this ` local object = CreateObject(model, 0, 0, 0, true, false, false) ` that might do it, if that works let me know.

i can see the prop attached to them but i dont see fire when they burn sadly i dont think you can ....

**Comment by jakeyboi1** [comment]
> > > > > you can sync the lightning by send it to al clients and make sure only the coords are set to the target. you can get the coords in server side before sending to all clients so whoever is cose will see it.
> > > > 
> > > > 
> > > > Just included this into the pr!
> > > 
> > > 
> > > works ! now just the fire and this is prefect but i love it so far !!
> > 
> > Replace line 208 in client.lua with this ` local object = CreateObject(model, 0, 0, 0, true, false, false) ` that might do it, if that works let me know.
> 
> i can see the prop attached to them but i dont see fire when they burn sadly i dont think you can .... 

Ah oh well. Atleast we got the lightning synced thanks to outsiders help. Hopefully this gets merged, I think its a really coold add on.

**Comment by James-the-Coding-Gamer** [comment]
maybe someday we can sync fire  but this is kool none the less

**Comment by devmiojo** [comment]
i like it

**Comment by outsider31000** [comment]
remove all the adventHandlers,  if you are not communicating from client to client and server to server, thats what they are for...
@jakeyboi1

**Comment by jakeyboi1** [comment]
> remove all the adventHandlers,  if you are not communicating from client to client and server to server, thats what they are for...
> @jakeyboi1 
> 

So to do that remove the handler and change the register to RegisterServerEvent('event-name', function()
End?

**Comment by outsider31000** [comment]
correct adventHandlers are not needed if you communicating from server to client and vice versa. keep the same structure the script already has.

**Comment by jakeyboi1** [comment]
> correct adventHandlers are not needed if you communicating from server to client and vice versa. keep the same structure the script already has.

Perfect I will do this when I get home. Never knew you could do that lol

**Comment by jakeyboi1** [comment]
Removed The Event Handlers!

**Pull request merged**
