### PR TITLE
Add noclip prompts translate

### PR DESCRIPTION
**Pull request by MasterTecknO**
Add noclip prompts translate

### CODE REVIEW

**Comment by outsider31000** [comment]
This is incomplete

**Comment by MasterTecknO** [comment]
Added translate on all languages

**Comment by outsider31000** [comment]
This is still incomplete,  where is the translation added to the prompts ?

**Comment by MasterTecknO** [comment]
Ouch!, sorry this is on another pull request, i add the change on this pull, i thought it was added to this.

**Comment by outsider31000** [comment]
this was reverted.

**Pull request merged**
