### PR TITLE
Added Padronized System of Traduction

### PR DESCRIPTION
**Pull request by cl3i550n**
- Added more languages.
- Mapped all code to translated.
- Small improves with inputs.

### CODE REVIEW

**Comment by outsider31000** [comment]
everything tested ?

**Comment by cl3i550n** [comment]
> everything tested ?

Yep... i tested during all day.
If any cause problem, i am here.

Captura de tela 2024-01-06 220210

**Comment by outsider31000** [comment]
This is a really big pr , but since is only about translation i'll merge this, because other scripts have it the same way and looks better , it's easy when they are all the same.

But a side note  usually I would not merge prs this large specially if they are a refactor, refactors are for the developers of the framework, just so you are aware, fixes or small implementations that's fine.
anything that requires large modifications of base code I suggest you make a version in your name if its really big changes just so you have it in your mind.

anyways thank you for this @cl3i550n community appreciates.

**Comment by cl3i550n** [comment]
> This is a really big pr , but since is only about translation i'll merge this, because other scripts have it the same way and looks better , it's easy when they are all the same.
> 
> But a side note  usually I would not merge prs this large specially if they are a refactor, refactors are for the developers of the framework, just so you are aware, fixes or small implementations that's fine.
> anything that requires large modifications of base code I suggest you make a version in your name if its really big changes just so you have it in your mind.
> 
> anyways thank you for this @cl3i550n community appreciates.

Thank you for your trust, I will be here to help with whatever you need.  Count on me!

**Pull request merged**
