### PR TITLE
Full hunger and thirst function

### PR DESCRIPTION
**Pull request by pepski1270**
This only works with fred metabolism script. Check config.lua

### CODE REVIEW

**Comment by outsider31000** [comment]
sorry but i cant accept this. fred metabolism isnt vorp official script we support vorp metabolism

**Comment by pepski1270** [comment]
yeah. i was wondering how can i use the vorp metabolism or is there a export like the fred script has.

**Comment by outsider31000** [comment]
vorp metabolism is already added to the heal function

**Comment by pepski1270** [comment]
does it have the export? i'll use it to refork this work

**Comment by outsider31000** [comment]
its already done. its added to the heal player and heals metabolism at the same time

**Comment by pepski1270** [comment]
it does heal. but full hunger and thirst is not working that's why i make this.

**Pull request closed without merging**
